export const FETCH_SHOPPING_LIST = "FETCH_SHOPPING_LIST";
export const FETCH_SHOPPING_LIST_SUCCESS = "FETCH_SHOPPING_LIST_SUCCESS";
export const SYNC_SHOPPING_LIST = "SYNC_SHOPPING_LIST";
export const SYNC_SHOPPING_LIST_STOP = "SYNC_SHOPPING_LIST_STOP";
